version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=bookmyroom
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - bookmyroom-network

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped
    networks:
      - bookmyroom-network

volumes:
  mongodb-data:

networks:
  bookmyroom-network:
    driver: bridge
