spring:
  application:
    name: book-my-room
  data:
    mongodb:
      uri: mongodb://mongodb:27017/bookmyroom

logging:
  level:
    root: INFO
    com.bookmyroom: DEBUG
    org.springframework.data.mongodb: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/bookmyroom.log
    max-size: 10MB
    max-history: 30

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000  # 24 hours in milliseconds 